#!/usr/bin/env bash
set -o errexit

candidates="request_log_analyzer request_log_analyzer-1.3.0"
testlogs="random-small.log random-big.log"

self_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
candidates_path="$self_path/../../target/release"
testlogs_path="$self_path"

function get_memory_usage_kbytes {
    command=$1
    result=$(/usr/bin/time -v $command 2>&1 | grep "Maximum resident set size" | grep --only-matching "[0-9]*$")
    echo $result
}

echo "Full parsing of each log file:"
for testlog  in $testlogs
do
    for candidate in $candidates
    do
        echo -en "$candidate\t$testlog\t"
        get_memory_usage_kbytes "$candidates_path/$candidate $testlogs_path/$testlog"
    done
done

echo -e "\n"
echo "Limited by -t 1 filter:"
for testlog  in $testlogs
do
    for candidate in $candidates
    do
        echo -en "$candidate\t$testlog\t"
        get_memory_usage_kbytes "$candidates_path/$candidate $testlogs_path/$testlog -t 1"
    done
done
